<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
$this->title = 'Matrix';
$this->params['breadcrumbs'] = array(
	array('label'=> 'Billing Matrix')
);
?>

<!-- this page specific styles -->
<?= Html::cssFile('@web/css/libs/dataTables.fixedHeader.css') ?>
<?= Html::cssFile('@web/css/libs/dataTables.tableTools.css') ?>

<?php
	$this->params['content_header_button'] = '';
?>

<div class="main-box">
	<div class="main-box-header">
	</div>
	<div class="main-box-body">
		<table id="table" class="table table-matrix table-bordered table-condensed">
			<thead>
				<tr>
					<th></th>
					<th>A01</th>
					<th>A02</th>
					<th>A03</th>
					<th>A04</th>
					<th>A05</th>
					<th>A06</th>
					<th>A07</th>
					<th>A08</th>
					<th>A09</th>
					<th>A10</th>
					<th>A11</th>
					<th>A12</th>
					<th>A13</th>
					<th>A14</th>
					<th>A15</th>
					<th>A16</th>
					<th>A17</th>
					<th>A18</th>
					<th>A19</th>
					<th>A20</th>
					<th>A21</th>
					<th>A22</th>
					<th>A23</th>
					<th>A24</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>B01</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B02</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B03</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B04</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B05</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B06</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B07</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B08</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B09</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B10</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B11</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B12</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B13</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B14</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B15</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B16</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B17</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B18</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B19</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B20</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B21</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B22</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B23</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>
				<tr>
					<td>B24</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
					<td>NW</td>
				</tr>

			</tbody>
		</table>
		<br>
	</div>
</div>



<!-- this page specific scripts -->
<?php $this->registerJsFile('@web/js/libs/jquery.dataTables.js', ['depends' => [\app\assets\AppAsset::className()]]); ?>
<?php $this->registerJsFile('@web/js/libs/dataTables.fixedColumns.js', ['depends' => [\app\assets\AppAsset::className()]]); ?>
<?php //$this->registerJsFile('@web/js/libs/dataTables.fixedHeader.js', ['depends' => [\app\assets\AppAsset::className()]]); ?>
<?php //$this->registerJsFile('@web/js/libs/dataTables.tableTools.js', ['depends' => [\app\assets\AppAsset::className()]]); ?>
<?php //$this->registerJsFile('@web/js/libs/jquery.dataTables.bootstrap.js', ['depends' => [\app\assets\AppAsset::className()]]); ?>
<?php $this->registerJsFile('@web/js/billing_matrix.js', ['depends' => [\app\assets\AppAsset::className()]]); ?>
